// Generated by https://quicktype.io

export interface Subjectevent {
    subjectgroup?: Subjectgroup;
}

export interface Subjectgroup {
    id: number;
    centralPolicyId: number;
    centralPolicy: null;
    provinceId: number;
    province: null;
    provincialDepartmentIdCreatedBy: number;
    provincialDepartment: null;
    createdBy: string;
    user: null;
    roleCreatedBy: number;
    status: string;
    type: string;
    land: string;
    suggestion: string;
    startDate: string;
    endDate: string;
    subjectNotificationDate: string;
    subjectDeadlineDate: string;
    peopleQuestionNotificationDate: string;
    peopleQuestionDeadlineDate: string;
    subjectCentralPolicyProvinces: SubjectCentralPolicyProvince[];
    subjectGroupPeopleQuestions: SubjectGroupPeopleQuestion[];
    answerRecommenDationInspectors: any[];
}

export interface SubjectCentralPolicyProvince {
    id: number;
    centralPolicyProvinceId: number;
    centralPolicyProvince: null;
    subjectGroupId: number;
    name: string;
    type: string;
    status: string;
    explanation: null;
    checkAnswer: number;
    createdAt: null;
    createdBy: string;
    updateAt: null;
    subjectDateCentralPolicyProvinces: null;
    //คำถาม
    subquestionCentralPolicyProvinces?: SubquestionCentralPolicyProvince[];
    subjectCentralPolicyProvinceFiles: null;
    suggestionSubjects: null;
}
//คำถาม
export interface SubquestionCentralPolicyProvince {
    id?: number;
    subjectCentralPolicyProvinceId?: number;
    name?: string;
    type?: string;
    box?: number;
    answerSubquestions?: AnswerSubquestion[];
    //ตัวเลือกคตำถาม
    subquestionChoiceCentralPolicyProvinces?: SubquestionChoiceCentralPolicyProvince[];
    subjectCentralPolicyProvinceGroups?: SubjectCentralPolicyProvinceGroup[];
    subjectCentralPolicyProvinceUserGroups?: any[];
    answerSubquestionOutsiders?: any[];
}

export interface AnswerSubquestion {
    id: number;
    subquestionCentralPolicyProvinceId: number;
    answerSubquestionStatusId: number;
    answerSubquestionStatus: AnswerSubquestionStatus;
    userId: string;
    user: User;
    answer: string;
    description: string;
    createdAt: string;
}

export interface AnswerSubquestionStatus {
    id: number;
    subjectCentralPolicyProvinceId: number;
    userId: string;
    user: User;
    status: string;
    createdAt: string;
}

export interface User {
    role_id: number;
    position: string;
    prefix: string;
    name: string;
    firstnameth: null | string;
    lastnameth: null | string;
    firstnameen: null;
    lastnameen: null;
    educational: null | string;
    birthday: string;
    officephonenumber: null | string;
    telegraphnumber: null | string;
    sideId: number;
    sides: null;
    ministryId: number;
    ministries: null;
    departmentId: number;
    departments: null;
    provincialDepartmentId: number;
    provincialDepartments: ProvincialDepartment | null;
    provinceId: number;
    province: null;
    districtId: number;
    district: null;
    subdistrictId: number;
    subdistricts: null;
    housenumber: null | string;
    rold: null | string;
    alley: null | string;
    postalcode: null | string;
    img: null | string;
    createdAt: string;
    startdate: string;
    enddate: null | string;
    active: number;
    userRegion: null;
    centralPolicyUser: null;
    userTokenMobiles: null;
    userProvince: null;
    notification: null;
    signature: null;
    commandnumber: null | string;
    commandnumberdate: null;
    fiscalYearId: number;
    autocreateuser: number;
    pw: string;
    id: string;
    userName: string;
    normalizedUserName: string;
    email: string;
    normalizedEmail: string;
    emailConfirmed: boolean;
    passwordHash: string;
    securityStamp: string;
    concurrencyStamp: string;
    phoneNumber: string;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEnd: null;
    lockoutEnabled: boolean;
    accessFailedCount: number;
}

export interface ProvincialDepartment {
    id: number;
    departmentId: number;
    department: null;
    name: string;
    createdAt: null;
}

export interface SubjectCentralPolicyProvinceGroup {
    id: number;
    subquestionCentralPolicyProvinceId: number;
    provincialDepartmentId: number;
    provincialDepartment: ProvincialDepartment;
}

export interface SubquestionChoiceCentralPolicyProvince {
    id: number;
    subquestionCentralPolicyProvinceId: number;
    name: string;
}

export interface SubjectGroupPeopleQuestion {
    id: number;
    subjectGroupId: number;
    centralPolicyEventId: number;
    centralPolicyEvent: null;
}
