// Generated by https://quicktype.io
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace InspecWeb.ViewModel.Otps
{


    public partial class ExternalOrganizationNew
    {
        [JsonProperty("Id")]
        public long Id { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Position")]
        public string Position { get; set; }

        [JsonProperty("PositionShort")]
        public string PositionShort { get; set; }

        [JsonProperty("Photo")]
        public string Photo { get; set; }

        [JsonProperty("Cabinet")]
        public Cabinet Cabinet { get; set; }

        [JsonProperty("FiscalYears")]
        public FiscalYear[] FiscalYears { get; set; }
    }

    public partial class Cabinet
    {
        [JsonProperty("Id")]
        public long Id { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }
    }

    public partial class FiscalYear
    {
        [JsonProperty("Year")]
        public long Year { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Projects")]
        public MinistersProjects Projects { get; set; }

        [JsonProperty("ProjectDetails")]
        public ProjectDetail[] ProjectDetails { get; set; }

        [JsonProperty("Regions")]
        public Cabinet[] Regions { get; set; }
    }

    public partial class ProjectDetail
    {
        [JsonProperty("Id")]
        public long Id { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("Status")]
        public string Status { get; set; }

        [JsonProperty("ProjectType")]
        public string ProjectType { get; set; }

        [JsonProperty("Minister")]
        public string Minister { get; set; }

        [JsonProperty("FiscalYear")]
        public string FiscalYear { get; set; }

        [JsonProperty("Region")]
        public string Region { get; set; }

        [JsonProperty("Province")]
        public string Province { get; set; }

        [JsonProperty("IsResidual")]
        public bool IsResidual { get; set; }

        [JsonProperty("Canceled")]
        public bool Canceled { get; set; }

        [JsonProperty("OverFlow")]
        public double OverFlow { get; set; }

        [JsonProperty("Associate")]
        public double Associate { get; set; }

        [JsonProperty("ProvideTypes")]
        public List<string> ProvideTypes { get; set; }

        [JsonProperty("ReceiveBudgetDate")]
        public DateTimeOffset? ReceiveBudgetDate { get; set; }

        [JsonProperty("EndDates")]
        public DateTimeOffset[] EndDates { get; set; }

        [JsonProperty("Procure")]
        public Procure Procure { get; set; }

        [JsonProperty("Progresses")]
        public Progress[] Progresses { get; set; }
    }

    public partial class Procure
    {
        [JsonProperty("OwnerName")]
        public string OwnerName { get; set; }

        [JsonProperty("Location")]
        public string Location { get; set; }

        [JsonProperty("Amount")]
        public double Amount { get; set; }

        [JsonProperty("StartDate")]
        public DateTimeOffset StartDate { get; set; }

        [JsonProperty("Remark")]
        public string Remark { get; set; }
    }

    public partial class Progress
    {
        [JsonProperty("SpentDate")]
        public DateTimeOffset SpentDate { get; set; }

        [JsonProperty("Spent")]
        public double Spent { get; set; }

        [JsonProperty("Percent")]
        public double Percent { get; set; }

        [JsonProperty("Remark")]
        public string Remark { get; set; }
    }

    public partial class MinistersProjects
    {
        [JsonProperty("Count")]
        public long Count { get; set; }

        [JsonProperty("Completed")]
        public long Completed { get; set; }

        [JsonProperty("TotalBudget")]
        public double TotalBudget { get; set; }

        [JsonProperty("TotalAmount")]
        public double TotalAmount { get; set; }

        [JsonProperty("TotalSpent")]
        public double TotalSpent { get; set; }

        [JsonProperty("TotalPercent")]
        public double TotalPercent { get; set; }
    }

    // // public enum RegionEnum { ครมคำสั่งที่1682562, คำสั่งที่1682562, คำสั่งที่2322561, คำสั่งที่3122559, คำสั่งที่3342560, เขตตรวจราชการที่1, เขตตรวจราชการที่10, เขตตรวจราชการที่11, เขตตรวจราชการที่12, เขตตรวจราชการที่13, เขตตรวจราชการที่14, เขตตรวจราชการที่15, เขตตรวจราชการที่16, เขตตรวจราชการที่17, เขตตรวจราชการที่18, เขตตรวจราชการที่2, เขตตรวจราชการที่3, เขตตรวจราชการที่4, เขตตรวจราชการที่5, เขตตรวจราชการที่6, เขตตรวจราชการที่7, เขตตรวจราชการที่8, เขตตรวจราชการที่9 };

    // // public enum FiscalYearEnum { ปีงบประมาณ2560, ปีงบประมาณ2561, ปีงบประมาณ2562, ปีงบประมาณ2563 };

    // // public enum ProjectType { การก่อสร้างโครงสร้างพื้นฐาน, อาชีพและสวัสดิการ, อิื่นๆด้านทรัพยากรธรรมชาติ, อิื่นๆด้านท่องเที่ยว, แหล่งน้ำ };

    // // public enum ProvideType { ดำเนินการเอง, วิธีกรณีพิเศษ, วิธีคัดเลือก, วิธีตกลงราคา, วิธีประกวดราคา, วิธีประกวดราคาด้วยวิธีการทางอิเล็กทรอนิกส์EBidding, วิธีประกวดราคาด้วยวิธีการทางอิเล็กทรอนิกส์EMarket, วิธีประกาศเชิญชวนทั่วไป, วิธีพิเศษ, วิธีสอบราคา, วิธีเฉพาะเจาะจง };

    // // public enum Status { กำลังดำเนินการ, จัดหาจัดซื้อจัดจ้าง, อยู่ระหว่างการเบิกจ่าย, เริ่มโครงการ, ได้รับงบประมาณ };

    // // public enum Position { รองนายกรัฐมนตรี, รัฐมนตรีประจําสํานักนายกรัฐมนตรี };

    // public enum PositionShort { รนรม, รมตนร };






}
