// Generated by https://quicktype.io
using Newtonsoft.Json;

namespace InspecWeb.ViewModel
{


    public partial class SubJectEventL
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("box")]
        public long Box { get; set; }

        [JsonProperty("answerSubquestions")]
        public object AnswerSubquestions { get; set; }

        [JsonProperty("subquestionChoiceCentralPolicyProvinces")]
        public object SubquestionChoiceCentralPolicyProvinces { get; set; }

        [JsonProperty("subjectCentralPolicyProvinceGroups")]
        public SubjectCentralPolicyProvinceGroupL[] SubjectCentralPolicyProvinceGroups { get; set; }
    }

    public partial class SubjectCentralPolicyProvinceGroupL
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("subquestionCentralPolicyProvinceId")]
        public long SubquestionCentralPolicyProvinceId { get; set; }

        [JsonProperty("provincialDepartmentId")]
        public long ProvincialDepartmentId { get; set; }

        [JsonProperty("provincialDepartment")]
        public ProvincialDepartmentL ProvincialDepartment { get; set; }
    }

    public partial class ProvincialDepartmentL
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("departmentId")]
        public long DepartmentId { get; set; }

        [JsonProperty("department")]
        public object Department { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("createdAt")]
        public object CreatedAt { get; set; }
    }
    public partial class SubjectProvinceCl
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("subquestionCentralPolicyProvinceId")]
        public long SubquestionCentralPolicyProvinceId { get; set; }

        [JsonProperty("provincialDepartmentId")]
        public long ProvincialDepartmentId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("box")]
        public long Box { get; set; }
    }
    // Generated by https://quicktype.io

    // namespace QuickType
    // {
    //     using System;
    //     using System.Collections.Generic;

    //     using System.Globalization;
    //     using Newtonsoft.Json;
    //     using Newtonsoft.Json.Converters;



    //     public partial class SubjectProvinceCl
    //     {
    //         public static SubjectProvinceCl FromJson(string json) => JsonConvert.DeserializeObject<SubjectProvinceCl>(json, QuickType.Converter.Settings);
    //     }

    //     public static class Serialize
    //     {
    //         public static string ToJson(this SubjectProvinceCl self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    //     }

    //     internal static class Converter
    //     {
    //         public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //         {
    //             MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //             DateParseHandling = DateParseHandling.None,
    //             Converters = {
    //                 new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //             },
    //         };
    //     }
    // }



}
