// Generated by https://quicktype.io

export interface PeopleModel {
    id: number;
    trainingId: number;
    userType: number;
    userId: string;
    provincialDepartmentId: number;
    provincialDepartments: null;
    userName: string;
    name: string;
    position: string;
    department: string;
    cardId: string;
    phone: string;
    email: string;
    status: number;
    group1: number;
    group2: number;
    group3: number;
    group4: number;
    group5: number;
    group6: number;
    group7: number;
    group8: number;
    group9: number;
    group10: number;
    type: string;
    nickname: string;
    retiredDate: string;
    birthDate: string;
    officeAddress: string;
    fax: string;
    collaboratorName: string;
    collaboratorPhone: string;
    collaboratorPhoneOffice: string;
    collaboratorEmail: string;
    training: Training;
    idCode: string;
    noIDCode: null;
    idCodeCreatedAt: null;
    createdAt: string;
    trainingRegisterConditions: null;
}

export interface Training {
    id: number;
    name: string;
    detail: string;
    location: null;
    generation: number;
    year: number;
    courseCode: number;
    startDate: string;
    endDate: string;
    regisStartDate: string;
    regisEndDate: string;
    image: string;
    status: number;
    createdAt: string;
    trainingSurveys: null;
}
