// Generated by https://quicktype.io

export interface Candibet {
    id:          number;
    name:        string;
    fiscalYears: FiscalYear[];
    ministers:   Minister[];
}

export interface FiscalYear {
    year:     number;
    name:     string;
    projects: Projects;
}

export interface Projects {
    count:        number;
    completed:    number;
    totalBudget:  number;
    totalAmount:  number;
    totalSpent:   number;
    totalPercent: number;
}

export interface Minister {
    year:          number;
    name:          string;
    position:      string;
    positionShort: string;
}
