// Generated by https://quicktype.io

export interface NewMinister {
    Id:            number;
    Name:          string;
    Position:      string;
    PositionShort: string;
    Photo:         string;
    Cabinet:       Cabinet;
    FiscalYears:   FiscalYear[];
}

export interface Cabinet {
    Id:   number;
    Name: string;
}

export interface FiscalYear {
    Year:           number;
    Name:           string;
    Projects:       Projects;
    ProjectDetails: ProjectDetail[];
    Regions:        Cabinet[];
}

export interface ProjectDetail {
    Id:                number;
    Name:              string;
    Description:       null | string;
    Status:            string;
    ProjectType:       string;
    Minister:          string;
    FiscalYear:        string;
    Region:            string;
    Province:          string;
    IsResidual:        boolean;
    Canceled:          boolean;
    OverFlow:          number;
    Associate:         number;
    ProvideTypes:      string[];
    ReceiveBudgetDate: string;
    EndDates:          string[];
    Procure:           Procure | null;
    Progresses:        Progress[];
}

export interface Procure {
    OwnerName: string;
    Location:  string;
    Amount:    number;
    StartDate: string;
    Remark:    null | string;
}

export interface Progress {
    SpentDate: string;
    Spent:     number;
    Percent:   number;
    Remark:    null | string;
}

export interface Projects {
    Count:        number;
    Completed:    number;
    TotalBudget:  number;
    TotalAmount:  number;
    TotalSpent:   number;
    TotalPercent: number;
}
