// Generated by https://quicktype.io

export interface ProvinceOtps {
        Id:              number;
        ISO:             string;
        Name:            string;
        EnglishName:     string;
        Seal:            string;
        Motto:           string;
        Tree:            string;
        Flower:          string;
        Latitude:        number;
        Longitude:       number;
        Special:         boolean;
        TownHallAddress: string;
        TownHallPhone:   string;
        Website:         string;
        CreatedAt:       string;
        UpdatedAt:       string;
}
