using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InspecWeb.Data;
using InspecWeb.Models;
using InspecWeb.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InspecWeb.Controllers
{
    [ApiController]
    public class UserController : ControllerBase
    {
        private static UserManager<ApplicationUser> _userManager;
        private static ApplicationDbContext _context;

        public UserController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }



        [Route("[controller]/[action]")]
        public async Task<string> Create()
        {
            string result = string.Empty;

            if (_context.Users.Count() == 0)
            {
                UserViewModel[] users = 
                    {
                          new UserViewModel { UserName ="admin@inspec.go.th", Email = "admin@inspec.go.th", Name ="Super Admin",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "Superadmin ",Prefix = "นาย",Role_id =1,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n1@inspec.go.th", Email = "userRole3n1@inspec.go.th",Name ="ชัยวัฒน์ โฆสิตาภา",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "พลเอก",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0899006901",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n2@inspec.go.th", Email = "userRole3n2@inspec.go.th",Name ="สุรุ่งลักษณ์ เมฆะอำนวยชัย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0816408221",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,13},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n3@inspec.go.th", Email = "userRole3n3@inspec.go.th",Name ="สุมิตรา อติศัพท์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0892057524 ",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3,15,18},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n4@inspec.go.th", Email = "userRole3n4@inspec.go.th",Name ="ณรงค์ เชื้อบุญช่วย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0982807576",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,10},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n5@inspec.go.th", Email = "userRole3n5@inspec.go.th",Name ="พีระ ทองโพธิ์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818380278",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {5,19},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n6@inspec.go.th", Email = "userRole3n6@inspec.go.th",Name ="ธสรณ์อัฑฒ์ ธนิทธิพันธ์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0854856845",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,8,11},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n7@inspec.go.th", Email = "userRole3n7@inspec.go.th",Name ="ปภัสมน อัมราลิขิต ",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818014534",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {7,17},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n8@inspec.go.th", Email = "userRole3n8@inspec.go.th",Name ="จิรายุ นันท์ธราธร",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0899697416",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,14},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n9@inspec.go.th", Email = "userRole3n9@inspec.go.th",Name ="อรนุช ศรีนนท์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0901972107",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,16},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n10@inspec.go.th", Email = "userRole3n10@inspec.go.th",Name ="ยงยุทธ สุทธิชื่น",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "611599888",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n11@inspec.go.th", Email = "userRole3n11@inspec.go.th",Name ="สุรุ่งลักษณ์ เมฆะอำนวยชัย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0846408221",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,13},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n12@inspec.go.th", Email = "userRole3n12@inspec.go.th",Name ="พันตำรวจโท เธียรรัตน์ วิเชียรสรรค์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0844392884",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n13@inspec.go.th", Email = "userRole3n13@inspec.go.th",Name ="ณรงค์ เชื้อบุญช่วย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0982807576",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,5},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n14@inspec.go.th", Email = "userRole3n14@inspec.go.th",Name ="ธสรณ์อัฑฒ์ ธนิทธิพันธ์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0854856845",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,8},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n15@inspec.go.th", Email = "userRole3n15@inspec.go.th",Name ="ปภัสมน อัมราลิขิต ",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818014534",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {7},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n16@inspec.go.th", Email = "userRole3n16@inspec.go.th",Name ="จิรายุ นันท์ธราธร",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0899697416",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,10},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n17@inspec.go.th", Email = "userRole3n17@inspec.go.th",Name ="อรนุช ศรีนนท์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0901972107",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n18@inspec.go.th", Email = "userRole3n18@inspec.go.th",Name ="สุมิตรา อติศัพท์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0892057524 ",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {14,15},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n19@inspec.go.th", Email = "userRole3n19@inspec.go.th",Name ="ดวงตา ตันโช",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0870654884",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n20@inspec.go.th", Email = "userRole3n20@inspec.go.th",Name ="พีระ ทองโพธิ์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818380278",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18,19},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n21@inspec.go.th", Email = "userRole3n21@inspec.go.th",Name ="พันตำรวจโท เธียรรัตน์ วิเชียรสรรค์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0844392884",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,3},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n22@inspec.go.th", Email = "userRole3n22@inspec.go.th",Name ="สุรุ่งลักษณ์ เมฆะอำนวยชัย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0846408221",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,13},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n23@inspec.go.th", Email = "userRole3n23@inspec.go.th",Name ="ณรงค์ เชื้อบุญช่วย",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0982807576",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,5,8},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n24@inspec.go.th", Email = "userRole3n24@inspec.go.th",Name ="ปภัสมน อัมราลิขิต ",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0854856845 ",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n25@inspec.go.th", Email = "userRole3n25@inspec.go.th",Name ="จิรายุ นันท์ธราธร",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0899697416",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,10},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n26@inspec.go.th", Email = "userRole3n26@inspec.go.th",Name ="อรนุช ศรีนนท์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0901972107",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n27@inspec.go.th", Email = "userRole3n27@inspec.go.th",Name ="กรีฑา สพโชค",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0892057524 ",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {14,15},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n28@inspec.go.th", Email = "userRole3n28@inspec.go.th",Name ="ดวงตา ตันโช",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0870654884",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){1} },
                          new UserViewModel { UserName ="userRole3n29@inspec.go.th", Email = "userRole3n29@inspec.go.th",Name ="พีระ ทองโพธิ์",MinistryId =1, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาย",Role_id =3,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818380278",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18,19},UserProvince = new List<int>(){1} },
                        new UserViewModel { UserName ="apai.s2509@gmail.com", Email = "apai.s2509@gmail.com",Name ="อภัย สุทธิสังข์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "(หัวหน้าผู้ตรวจราชการ) กำกับดูแลภาพรวมทุกกลุ่มสินค้า ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818864",PhoneNumber = "0816415234",Telegraphnumber = "022829921",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ploenjit7663@gmail.com", Email = "ploenjit7663@gmail.com",Name ="เพลินจิตต์ พรหมหิตาธร",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818864",PhoneNumber = "0982847669",Telegraphnumber = "022829921",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="pongocky@gmail.com", Email = "pongocky@gmail.com",Name ="พงศกร นุตยะสกุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818864",PhoneNumber = "0846448562",Telegraphnumber = "022829921",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n4@inspec.go.th", Email = "userRole6n4@inspec.go.th",Name ="นลิน บุญสพ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818864",PhoneNumber = "0853604040",Telegraphnumber = "022829921",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ppongsapitch@gmail.com", Email = "ppongsapitch@gmail.com",Name ="พิศาล พงศาพิชณ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมการข้าว / มกอช. ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022826863",PhoneNumber = "0898868980",Telegraphnumber = "022823552",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="mahathein.an@gmail.cpm", Email = "mahathein.an@gmail.cpm",Name ="อัญชลี มหาเทียน",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022826863",PhoneNumber = "0818401292",Telegraphnumber = "022823552",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n7@inspec.go.th", Email = "userRole6n7@inspec.go.th",Name ="ต่อพร สัตบุษ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022826863",PhoneNumber = "0830197219",Telegraphnumber = "022823552",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="wprompoj@moac.go.th", Email = "wprompoj@moac.go.th",Name ="วราภรณ์ พรหมพจน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "การส่งเสริมสหกรณ์ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "026299058",PhoneNumber = "0850706477",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,3},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="jubjang645@gmail.com", Email = "jubjang645@gmail.com",Name ="สุพัตรา ผลรัตนไพบูลย์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "026299058",PhoneNumber = "0847230033",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,3},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n10@inspec.go.th", Email = "userRole6n10@inspec.go.th",Name ="ธัญลักษณ์ ดีปินตา",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "026299058",PhoneNumber = "0876576398",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1,3},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n11@inspec.go.th", Email = "anut@moac.go.th",Name ="อานัติ วิเศษรจนา",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สำนักการปฏิรูปที่ดินเพื่อเกษตรกรรม ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022801745",PhoneNumber = "0844508512",Telegraphnumber = "022801745",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n12@inspec.go.th", Email = "sipraya001@gmail.com",Name ="โสมสุทธา ภัสสรปกณกิจ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022801745",PhoneNumber = "0922598909",Telegraphnumber = "022801745",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n13@inspec.go.th", Email = "pimolbutrm@yahoo.com",Name ="อุมาพร พิมลบุตร",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "082823559",PhoneNumber = "0827006202",Telegraphnumber = "022811553",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n14@inspec.go.th", Email = "fiem2548@gmail.com",Name ="อำพร ระดมบุญ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "082823559",PhoneNumber = "0614173070",Telegraphnumber = "022811553",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n15@inspec.go.th", Email = "userRole6n15@inspec.go.th",Name ="สุวดี พิมพขันธ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผต.นร. ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "082823559",PhoneNumber = "0633932153",Telegraphnumber = "022811553",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="Kem_Y@yahoo.com", Email = "Kem_Y@yahoo.com",Name ="เข้มแข็ง ยุติธรรมดำรง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมพัฒนาที่ดิน ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022810856",PhoneNumber = "0818773844",Telegraphnumber = "026299646",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {8,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="m.kmutt@hotmail.com", Email = "m.kmutt@hotmail.com",Name ="สุทธิลักษณ์ ชนะสุข",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022810856",PhoneNumber = "0830812311",Telegraphnumber = "026299646",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {8,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n16@inspec.go.th", Email = "userRole6n16@inspec.go.th",Name ="สำราญ คมศรี",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022810856",PhoneNumber = "0899960941",Telegraphnumber = "026299646",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {8,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="CWARAWUT@YMAIL.COM", Email = "CWARAWUT@YMAIL.COM",Name ="วราวุธ ชูธรรมธัช",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สำนักงานเศรษฐกิจการเกษตร ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022821728",PhoneNumber = "0899276371",Telegraphnumber = "022813741",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="m.kokan1234@gmail.com", Email = "m.kokan1234@gmail.com",Name ="มุกดา กอกัน",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022821728",PhoneNumber = "0910324271",Telegraphnumber = "022813741",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =1,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n17@inspec.go.th", Email = "userRole6n17@inspec.go.th",Name ="เกรียงศักดิ์ ชาติปรีดี",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022821728",PhoneNumber = "0899431515",Telegraphnumber = "022813741",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =2,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {9,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="komsan@moac.go.th", Email = "komsan@moac.go.th",Name ="คมสัน จำรูญพงษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมชลประทาน/กรมวิชการเกษตร ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823496",PhoneNumber = "0947829515",Telegraphnumber = "022810857",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =3,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="reraikh78@gmail.com", Email = "reraikh78@gmail.com",Name ="เรไร คีรีต๊ะ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823496",PhoneNumber = "0818748809",Telegraphnumber = "022810857",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =4,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n18@inspec.go.th", Email = "userRole6n18@inspec.go.th",Name ="ปิยะนันท์ เพ็งสกุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823496",PhoneNumber = "0955081075",Telegraphnumber = "022810857",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =5,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="Krishnapong.s@gmail.com", Email = "Krishnapong.s@gmail.com",Name ="กฤษณพงศ์ ศรีพงษ์พันธุ์กุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมหม่อนไหม ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022828422",PhoneNumber = "0854854506",Telegraphnumber = "026299649",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =6,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="rutthip.t@rice.mail.go.th", Email = "rutthip.t@rice.mail.go.th",Name ="รัฐธิภา ธนารักษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022828422",PhoneNumber = "0878136262",Telegraphnumber = "026299649",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =7,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="pik4669068@gmail.com", Email = "pik4669068@gmail.com",Name ="ปิยะฉัตร พุทธาวงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022828422",PhoneNumber = "0632059637",Telegraphnumber = "026299649",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =8,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="utt001@hotmail.com", Email = "utt001@hotmail.com",Name ="ปราโมทย์ ยาใจ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมฝนหลวงและการบินเกษตร ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022816933",PhoneNumber = "0827628357",Telegraphnumber = "026299648",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =9,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {14,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="kanokvan13@gmail.com", Email = "kanokvan13@gmail.com",Name ="กนกวรรณ จำปาทอง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022816933",PhoneNumber = "0925269291",Telegraphnumber = "026299648",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =10,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {14,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n19@inspec.go.th", Email = "userRole6n19@inspec.go.th",Name ="วัฒนา พัฒนถาวร",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022816933",PhoneNumber = "0846801571",Telegraphnumber = "026299648",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =11,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {14,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="sudsakorn_999@hotmail.com", Email = "sudsakorn_999@hotmail.com",Name ="สุดสาคร ภัทรกุลนิษฐ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมส่งเสริมการเกษตร ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823464",PhoneNumber = "0814842673",Telegraphnumber = "022823566",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =12,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="naree.trongkong@gmail.com", Email = "naree.trongkong@gmail.com",Name ="นารีนัตท์ฎา ตรงคง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823464",PhoneNumber = "0838231901",Telegraphnumber = "022823566",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =13,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n20@inspec.go.th", Email = "userRole6n20@inspec.go.th",Name ="อรรณพ สอนชา",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022823464",PhoneNumber = "0616416090",Telegraphnumber = "022823566",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =14,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="weerachart.kh@gmail.com", Email = "weerachart.kh@gmail.com",Name ="วีรชาติ เขื่อนรัตน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "กรมปศุสัตว์ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818936",PhoneNumber = "0812888882",Telegraphnumber = "022818936",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =15,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {17,18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="janjila2513@gmail.com", Email = "janjila2513@gmail.com",Name ="จันจิฬา สังข์ทอง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818936",PhoneNumber = "0942907094",Telegraphnumber = "022818936",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =16,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {17,18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n21@inspec.go.th", Email = "userRole6n21@inspec.go.th",Name ="อลิษา สายแผ้ว",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "เจ้าหน้าที่สนับสนุนการตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "022818936",PhoneNumber = "0914965190",Telegraphnumber = "022818936",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =17,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {17,18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="drthong@gmail.com", Email = "drthong@gmail.com",Name ="ธงชัย เลิศวิไลรัตนพงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901467",PhoneNumber = "0817985544",Telegraphnumber = "025901431",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =17,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="chokekird.p@gmail.com", Email = "chokekird.p@gmail.com",Name ="ภูวิวรรธน์ โชคเกิด",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "รอ.นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0934488745",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =18,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="prinda9999@gmail.com", Email = "prinda9999@gmail.com",Name ="ปริญดา ทุนคำ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยกลุ่มตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0615509529",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =19,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="kosumny@gmail.com", Email = "kosumny@gmail.com",Name ="โกสุม สาลี",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901228",PhoneNumber = "0925163553",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =20,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {16,17},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ypanumard@yahoo.com", Email = "ypanumard@yahoo.com",Name ="ภาณุมาศ ญาณเวทย์สกุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025908432",PhoneNumber = "0945929229",Telegraphnumber = "025908532",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =21,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="chaiynan@yahoo.com", Email = "chaiynan@yahoo.com",Name ="ไชยนันท์ ทยาวิวัฒน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901600",PhoneNumber = "0819528145",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="yolk@health.moph.go.th", Email = "yolk@health.moph.go.th",Name ="พินทุสร เหมพิสุทธิ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0898876188",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="Surut_moph@hotmail.com", Email = "Surut_moph@hotmail.com",Name ="สุรัติ ฉัตรไชยาฤกษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901015",PhoneNumber = "0816466620",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {18},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="boonchai65@gmail.com", Email = "boonchai65@gmail.com",Name ="บุญชัย ธีระกาญจน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้าผู้ตรวจราขการกระทรวงสาธารณสุข ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901591",PhoneNumber = "0898561767",Telegraphnumber = "025911690",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="somroon1@gmail.com", Email = "somroon1@gmail.com",Name ="สมเกียติ ขำนุรักษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901479",PhoneNumber = "0818877270",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="dhpanita62@gmail.com", Email = "dhpanita62@gmail.com",Name ="ปนิตา ธีรสฤษกุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "056334426",PhoneNumber = "0848744091",Telegraphnumber = "056334426",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="tapanapon11@gmail.com", Email = "tapanapon11@gmail.com",Name ="ฐปณภร เจริญวงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0843883041",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,19},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="wisedsak2@gmail.com", Email = "wisedsak2@gmail.com",Name ="สุระ วิเศษศักดิ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025902585",PhoneNumber = "0902627007",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,3,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ssrijaranai@gmail.com", Email = "ssrijaranai@gmail.com",Name ="สมยศ ศรีจารนัย",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901470",PhoneNumber = "0899354797",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,3,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="j_aeww@hotmail.com", Email = "j_aeww@hotmail.com",Name ="อังคณา จรรยากุลวงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901470",PhoneNumber = "0848744087",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,3,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="atichat19@gmail.com", Email = "atichat19@gmail.com",Name ="อติชาต หงษ์ทอง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901470",PhoneNumber = "0813643341",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {2,3,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ampornbenja@yahoo.com", Email = "ampornbenja@yahoo.com",Name ="อัมพร เบญจพลพิทักษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "พญ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901587",PhoneNumber = "0818605945",Telegraphnumber = "025911475",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3,4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="kittisny@gmail.com", Email = "kittisny@gmail.com",Name ="กิตติ กรรภิรมย์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901582",PhoneNumber = "0647894519",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3,4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="jarupa2010@gmail.com", Email = "jarupa2010@gmail.com",Name ="จารุภา จำนงศักดิ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025902461",PhoneNumber = "0817452564",Telegraphnumber = "025902468",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3,4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="jubsuphan@gmail.com", Email = "jubsuphan@gmail.com",Name ="อมรรัตน์ ลิ้มจิตสมบูรณ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0628246415",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {3,4,5},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="sunbs22@gmail.com", Email = "sunbs22@gmail.com",Name ="สุเทพ เพชรมาก",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901487",PhoneNumber = "0818771744",Telegraphnumber = "025918529",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="aphichatrodsom@yahoo.com", Email = "aphichatrodsom@yahoo.com",Name ="อภิชาติ รอดสม",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901603",PhoneNumber = "0819988620",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="paranee.w@gmail.com", Email = "paranee.w@gmail.com",Name ="ภารณี วสุเสถียร",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0928946544",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="padhigorn13@hotmail.com", Email = "padhigorn13@hotmail.com",Name ="พัฒฑิกรณ์ ทองคำ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0897270832",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {4,10},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="svibhan@gmail.com", Email = "svibhan@gmail.com",Name ="วิพรรณ สังคหะพงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "พญ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901610",PhoneNumber = "0818685388",Telegraphnumber = "025908534",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n22@inspec.go.th", Email = "userRole6n22@inspec.go.th",Name ="อุดม ภู่วโรดม",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901608",PhoneNumber = "0865335325",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="aiamma@hotmail.com", Email = "aiamma@hotmail.com",Name ="ชาลี เอี่ยมมา",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาย",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0613955353",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="pen.ta@hotmail.com", Email = "pen.ta@hotmail.com",Name ="ศิริเพ็ญ ตลับนาค",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901604",PhoneNumber = "0894744916",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {13},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="chanvitt@gmail.com", Email = "chanvitt@gmail.com",Name ="ชาญวิทย์ ทระเทพ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901474",PhoneNumber = "0896092250",Telegraphnumber = "025901496",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="sa.apiw@gmail.com", Email = "sa.apiw@gmail.com",Name ="สวัสดิ์ อภิวัจนีวงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901481",PhoneNumber = "0898563535",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="krarok@hotmail.com", Email = "krarok@hotmail.com",Name ="สิริพรรณ โชติกมาศ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0856676333",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="sudaratana789@gmail.com", Email = "sudaratana789@gmail.com",Name ="สุภาพร เฉยทิม",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901474",PhoneNumber = "0818195279",Telegraphnumber = "025901496",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {11,12},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n23@inspec.go.th", Email = "userRole6n23@inspec.go.th",Name ="พงศ์เกษม ไข่มุกด์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0819787532",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="anitiapin@hotmail.com", Email = "anitiapin@hotmail.com",Name ="อัจฉรา นิธิอภิญญาสกุล",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "พญ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901490",PhoneNumber = "0933563941",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="poo1965@hotmail.com", Email = "poo1965@hotmail.com",Name ="จุฑารัตน์ มากคงแก้ว",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "044244089",PhoneNumber = "0869782462",Telegraphnumber = "044245188",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="bonita2546@hotmail.com", Email = "bonita2546@hotmail.com",Name ="พรอนันต์ กิตติมั่นคง",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "044244089",PhoneNumber = "0929966563",Telegraphnumber = "044245188",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="thongchaiboss@gmail.com", Email = "thongchaiboss@gmail.com",Name ="ธงชัย กีรติหัตถยากร",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "029501589",PhoneNumber = "0818952244",Telegraphnumber = "025901690",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="2043visa@gmail.com", Email = "2043visa@gmail.com",Name ="ทวีศิลป์ วิษณุโยธิน",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901483",PhoneNumber = "0898139393",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n24@inspec.go.th", Email = "userRole6n24@inspec.go.th",Name ="ถาวร สกุลพาณิชย์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818283850",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="kongmanee@hotmail.com", Email = "kongmanee@hotmail.com",Name ="กองมณี สุรวงษ์สิน",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0848744090",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {12,15},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="pitakpolb@hotmail.com", Email = "pitakpolb@hotmail.com",Name ="พิทักษ์พล บุณยมาลิก",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901462",PhoneNumber = "0883988810",Telegraphnumber = "025908534",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="wanchai25035088@hotmail.com", Email = "wanchai25035088@hotmail.com",Name ="วันชัย เหล่าเสถียรกิจ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0818775766",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="userRole6n25@inspec.go.th", Email = "userRole6n25@inspec.go.th",Name ="จงกลนี จริยานุวัฒน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0843618707",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="wasana.chot@gmail.com", Email = "wasana.chot@gmail.com",Name ="วาสนา โชติชะวารานนท์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0896985588",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="Jc72012@gmail.com", Email = "Jc72012@gmail.com",Name ="เจษฎา ฉายคุณรัฐ",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901583",PhoneNumber = "0899739936",Telegraphnumber = "025901690",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7,8},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="trayanan12@gmail.com", Email = "trayanan12@gmail.com",Name ="สุนันทา กาญจนพงศ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0815356272",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7,8},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="praves72@hotmail.com", Email = "praves72@hotmail.com",Name ="ประเวศ หมีดเส็น",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ช่วยผู้ตรวจราชการ ",Prefix = "ภก.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "074441373",PhoneNumber = "0892940505",Telegraphnumber = "074441374",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7,8},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="srakngarn@gmail.com", Email = "srakngarn@gmail.com",Name ="ศิญาภัสร์ จำรัสอธิวัฒน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นางสาว",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0819287269",Telegraphnumber = "025902468",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {6,7,8},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="ampornbenja@yahoo.com", Email = "ampornbenja@yahoo.com",Name ="อัมพร เบญจพลพิทักษ์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "ผู้ตรวจราชการกระทรวง ",Prefix = "พญ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901587",PhoneNumber = "0818605945",Telegraphnumber = "025911475",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="kittisny@gmail.com", Email = "kittisny@gmail.com",Name ="กิตติ กรรภิรมย์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "สาธารณสุขนิเทศก์ ",Prefix = "นพ.",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "025901582",PhoneNumber = "0647894519",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },
                        new UserViewModel { UserName ="vilirat2004@hotmail.com", Email = "vilirat2004@hotmail.com",Name ="วาสนา วิไลรัตน์",MinistryId =7, DistrictId =1,ProvinceId =1,SubdistrictId =1,Position = "หัวหน้ากลุ่มตรวจราชการ ",Prefix = "นาง",Role_id =6,Educational = "",Birthday =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null),Officephonenumber = "",PhoneNumber = "0901987604",Telegraphnumber = "",Housenumber = "",Rold = "",Alley = "", Postalcode = "",Side = "", Img = "",Active =22,CreatedAt = DateTime.Now,Startdate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), Enddate =DateTime.ParseExact("1957/10/22 00:00:00", "yyyy/MM/dd HH:mm:ss", null), UserRegion = new List<int>() {1},UserProvince = new List<int>(){} },


                    };

                
                foreach (var item in users) {
                    var user = new ApplicationUser { UserName = item.UserName, Email = item.Email };

                    var success = await _userManager.CreateAsync(user, "Admin@12345678").ConfigureAwait(false);

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user).ConfigureAwait(false);
                    await _userManager.ConfirmEmailAsync(user, code).ConfigureAwait(false);

                    user.DistrictId = item.DistrictId;
                    user.ProvinceId = item.ProvinceId;
                    user.SubdistrictId = item.SubdistrictId;
                    user.MinistryId = item.MinistryId;
                    user.Position = item.Position;
                    user.Prefix = item.Prefix;
                    user.Name = item.Name;
                    user.Role_id = item.Role_id;
                    user.Educational = item.Educational;
                    user.Birthday = item.Birthday;
                    user.Officephonenumber = item.Officephonenumber;
                    user.PhoneNumber = item.PhoneNumber;
                    user.Telegraphnumber = item.Telegraphnumber;
                    user.Housenumber = item.Housenumber;
                    user.Rold = item.Rold;
                    user.Alley = item.Alley;
                    user.Postalcode = item.Postalcode;
                    user.Side = item.Side;
                    user.Img = item.Img;
                    user.CreatedAt = item.CreatedAt;
                    user.Startdate = item.Startdate;
                    user.Enddate = item.Enddate;
                    user.Active = item.Active;

                    _context.Entry(user).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    _context.SaveChanges();

                                
                        foreach (var item2 in item.UserRegion)
                        {
                            var userregiondata = new UserRegion
                            {
                                UserID = user.Id,
                                RegionId = item2
                            };
                            _context.UserRegions.Add(userregiondata);
                            _context.SaveChanges();
                        }

                    foreach (var item3 in item.UserProvince)
                    {
                        var userprovincedata = new UserProvince
                        {
                            UserID = user.Id,
                            ProvinceId = item3
                        };
                        _context.UserProvinces.Add(userprovincedata);
                        _context.SaveChanges();
                    }


                }
                result = "Success";             
            }
            else
            {
                result = "Fail";
            }

            return result;
        }

        [HttpGet("api/[controller]/[action]/{id}")]
        public IEnumerable<ApplicationUser> getuser(long id)
        {
            var users = _context.Users
                .Include(s => s.UserRegion)
                .ThenInclude(r => r.Region)
                .Where(m => m.Role_id == id);
                
            return users;
        }
    }
}