// Generated by https://quicktype.io

export interface Executiveordercommanded {
    id:                    number;
    userID:                string;
    user:                  null;
    subject:               string;
    subjectdetail:         string;
    createdAt:             string;
    commanded_date:        string;
    publics:               number;
    draft:number;
    cancel:number;
    accept:number;
    canceldetail:string;
    executiveOrderFiles:   ExecutiveOrderFile[];
    executiveOrderAnswers: ExecutiveOrderAnswer[];
}

export interface ExecutiveOrderAnswer {
    id:                        number;
    executiveOrderId:          number;
    status:                    string;
    userID:                    string;
    user:                      any;
    answerdetail:              null;
    answerProblem:             null;
    answerCounsel:             null;
    beaware_date:              null;
    publics:                   number;
    answerExecutiveOrderFiles: null;

    
}

export interface ExecutiveOrderFile {
    id:               number;
    executiveOrderId: number;
    name:             string;
}
