// Generated by https://quicktype.io

export interface Region {
    Id:          number;
    Name:        string;
    FiscalYears: FiscalYear[];
}

export interface FiscalYear {
    Year:      number;
    Name:      Name;
    Projects:  Projects;
    Provinces: Province[];
}

export enum Name {
    ปีงบประมาณ2560 = "ปีงบประมาณ 2560",
    ปีงบประมาณ2561 = "ปีงบประมาณ 2561",
    ปีงบประมาณ2562 = "ปีงบประมาณ 2562",
    ปีงบประมาณ2563 = "ปีงบประมาณ 2563",
}

export interface Projects {
    Count:        number;
    Completed:    number;
    TotalBudget:  number;
    TotalAmount:  number;
    TotalSpent:   number;
    TotalPercent: number;
}

export interface Province {
    Id:   number;
    Name: string;
}
