// Generated by https://quicktype.io

export interface Report1 {
  subjectdata: Subjectdatum[];
}

export interface Subjectdatum {
  id:                                number;
  centralPolicyProvinceId:           number;
  centralPolicyProvince:             CentralPolicyProvince;
  subjectGroupId:                    number;
  subjectGroup:                      null;
  name:                              string;
  type:                              string;
  status:                            string;
  explanation:                       string;
  subjectDateCentralPolicyProvinces: null;
  subquestionCentralPolicyProvinces: SubquestionCentralPolicyProvince[];
  subjectCentralPolicyProvinceFiles: null;
  suggestionSubjects:                null;
}

export interface CentralPolicyProvince {
  id:                            number;
  centralPolicyId:               number;
  centralPolicy:                 CentralPolicy;
  provinceId:                    number;
  province:                      Province;
  step:                          string;
  status:                        string;
  questionPeople:                null;
  subjectCentralPolicyProvinces: any[];
  answerCentralPolicyProvinces:  null;
}

export interface CentralPolicy {
  id:                     number;
  fiscalYearId:           number;
  fiscalYear:             null;
  title:                  string;
  startDate:              string;
  endDate:                string;
  createdAt:              string;
  createdBy:              string;
  status:                 string;
  type:                   string;
  class:                  string;
  subjects:               null;
  centralPolicyFiles:     null;
  centralPolicyUser:      null;
  centralPolicyDates:     null;
  centralPolicyProvinces: any[];
  centralPolicyEvents:    null;
}

export interface Province {
  id:        number;
  name:      string;
  link:      string;
  createdAt: null;
}

export interface SubquestionCentralPolicyProvince {
  id:                                      number;
  subjectCentralPolicyProvinceId:          number;
  name:                                    string;
  type:                                    string;
  box:                                     number;
  answerSubquestions:                      null;
  subquestionChoiceCentralPolicyProvinces: null;
  subjectCentralPolicyProvinceGroups:      SubjectCentralPolicyProvinceGroup[];
  subjectCentralPolicyProvinceUserGroups:  null;
  answerSubquestionOutsiders:              null;
}

export interface SubjectCentralPolicyProvinceGroup {
  id:                                 number;
  subquestionCentralPolicyProvinceId: number;
  provincialDepartmentId:             number;
  provincialDepartment:               ProvincialDepartment;
}

export interface ProvincialDepartment {
  id:           number;
  departmentId: number;
  department:   null;
  name:         string;
  createdAt:    null;
}
