// Generated by https://quicktype.io

export interface CentralPolicyProvince {
    id:                            number;
    centralPolicyId:               number;
    centralPolicy:                 null;
    provinceId:                    number;
    province:                      null;
    step:                          string;
    status:                        string;
    questionPeople:                null;
    subjectCentralPolicyProvinces: null;
    answerCentralPolicyProvinces:  Answerrole7List[];
}

export interface Answerrole7List {
    id:                           number;
    centralPolicyProvinceId:      number;
    centralPolicyProvince?:       CentralPolicyProvince;
    centralPolicyEventQuestionId: number;
    centralPolicyEventQuestion:   CentralPolicyEventQuestion;
    userId:                       string;
    user:                         null;
    answer:                       string;
    createdAt:                    string;
}

export interface CentralPolicyEventQuestion {
    id:                   number;
    centralPolicyEventId: number;
    centralPolicyEvent:   null;
    questionPeople:       string;
    notificationDate:     string;
    deadlineDate:         string;
}
