// Generated by https://quicktype.io

export interface ReportCentralPolicy {
    centralpolicydata: Centralpolicydata;
    user:              User;
}

export interface Centralpolicydata {
    id:                     number;
    fiscalYearId:           number;
    fiscalYear:             null;
    title:                  string;
    startDate:              string;
    endDate:                string;
    createdAt:              string;
    createdBy:              string;
    status:                 string;
    type:                   string;
    class:                  string;
    subjects:               null;
    centralPolicyFiles:     null;
    centralPolicyUser:      null;
    centralPolicyDates:     null;
    centralPolicyProvinces: CentralPolicyProvince[];
    centralPolicyEvents:    null;
}

export interface CentralPolicyProvince {
    id:                            number;
    centralPolicyId:               number;
    provinceId:                    number;
    province:                      Province;
    step:                          string;
    status:                        string;
    questionPeople:                null;
    subjectCentralPolicyProvinces: SubjectCentralPolicyProvince[];
    answerCentralPolicyProvinces:  null;
}

export interface Province {
    id:        number;
    name:      string;
    link:      string;
    createdAt: null;
}

export interface SubjectCentralPolicyProvince {
    id:                                number;
    centralPolicyProvinceId:           number;
    subjectGroupId:                    number;
    subjectGroup:                      null;
    name:                              string;
    type:                              string;
    status:                            string;
    explanation:                       string;
    subjectDateCentralPolicyProvinces: null;
    subquestionCentralPolicyProvinces: SubquestionCentralPolicyProvince[];
    subjectCentralPolicyProvinceFiles: null;
    suggestionSubjects:                null;
}

export interface SubquestionCentralPolicyProvince {
    id:                                      number;
    subjectCentralPolicyProvinceId:          number;
    name:                                    string;
    type:                                    string;
    box:                                     number;
    answerSubquestions:                      null;
    subquestionChoiceCentralPolicyProvinces: null;
    subjectCentralPolicyProvinceGroups:      SubjectCentralPolicyProvinceGroup[];
    subjectCentralPolicyProvinceUserGroups:  null;
    answerSubquestionOutsiders:              null;
}

export interface SubjectCentralPolicyProvinceGroup {
    id:                                 number;
    subquestionCentralPolicyProvinceId: number;
    provincialDepartmentId:             number;
    provincialDepartment:               ProvincialDepartment;
}

export interface ProvincialDepartment {
    id:           number;
    departmentId: number;
    department:   null;
    name:         string;
    createdAt:    null;
}

export interface User {
    role_id:                number;
    position:               string;
    prefix:                 string;
    name:                   string;
    educational:            string;
    birthday:               string;
    officephonenumber:      string;
    telegraphnumber:        string;
    side:                   string;
    ministryId:             number;
    ministries:             null;
    departmentId:           number;
    departments:            Departments;
    provincialDepartmentId: number;
    provincialDepartments:  null;
    provinceId:             number;
    province:               Province;
    districtId:             number;
    district:               null;
    subdistrictId:          number;
    subdistricts:           null;
    housenumber:            string;
    rold:                   string;
    alley:                  string;
    postalcode:             string;
    img:                    string;
    createdAt:              string;
    startdate:              string;
    enddate:                string;
    active:                 number;
    userRegion:             null;
    centralPolicyUser:      null;
    userProvince:           null;
    notification:           null;
    id:                     string;
    userName:               string;
    normalizedUserName:     string;
    email:                  string;
    normalizedEmail:        string;
    emailConfirmed:         boolean;
    passwordHash:           string;
    securityStamp:          string;
    concurrencyStamp:       string;
    phoneNumber:            string;
    phoneNumberConfirmed:   boolean;
    twoFactorEnabled:       boolean;
    lockoutEnd:             null;
    lockoutEnabled:         boolean;
    accessFailedCount:      number;
}

export interface Departments {
    id:         number;
    ministryId: number;
    ministries: null;
    name:       string;
    createdAt:  null;
}
